# -*- coding: utf-8 -*-
"""Q5_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19fLBYgrxvEcH2qfm0URlFaLuEUyLMibB
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from preprocessing.polynomial_features import PolynomialFeatures
from linearRegression.linear_regression import LinearRegression
import os.path
from os import path
from sklearn.preprocessing import StandardScaler

np.random.seed(45)  #Setting seed for reproducibility

if not path.exists('Plots/Question5/'):
    os.makedirs('Plots/Question5/')

# TODO : Write here
plt.figure(dpi = 150)
datapoints = []
for i in range(1,5):
    x = np.array([i*np.pi/180 for i in range(50,10**(i+1)+50)])
    y = 3*x + 8 + np.random.normal(0,3,len(x))
    datapoints.append(len(x))
    deg = np.array([i for i in range(1, 10, 2)])
    coef = []
    for i in deg:
        poly = PolynomialFeatures(degree=i, include_bias=True)
        X_poly = poly.transform(x)
        scaler = StandardScaler()
        X_poly = scaler.fit_transform(X_poly)
        LR = LinearRegression(fit_intercept=True)
        LR.fit_sklearn_LR(X_poly,y)
        coef.append(np.linalg.norm(LR.coef_))

    coef = np.array(coef)
    plt.plot(deg, np.log(coef))


plt.title("Log Norm of Theta v/s Degree For different datasize")
plt.xlabel("Degree")
plt.ylabel("Log of Coefficient Norm")
plt.legend(datapoints)
plt.savefig('Plots/Question5/DegreeDatasetPlotLog.png')
plt.show()
