# -*- coding: utf-8 -*-
"""Q6_input_normalize.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f7kCUuDOHfftApIrWG1t-OUn2FVdaxeV
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from linearRegression.linear_regression import LinearRegression
from linearRegression.metrics import *
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_diabetes

#TODO : Write here

import warnings
warnings.warn('Warning Message: This is a warning message')
warnings.simplefilter("ignore")

np.random.seed(45)

X, y = load_diabetes(return_X_y = True, scaled=False)

LR = LinearRegression(fit_intercept=True)
LR.fit_sklearn_LR(X,y)
y_hat = LR.predict(X)

print('For sklearn LinearRegression Unnormalized Data : \n')
print('RMSE: ', rmse(y_hat, y))
print('MAE: ', mae(pd.Series(y_hat), pd.Series(y)))
print("---------------------------")

LR = LinearRegression(fit_intercept=True)
scaler = StandardScaler()
X = scaler.fit_transform(X)
LR.fit_sklearn_LR(X,y)
y_hat = LR.predict(X)

print('For sklearn LinearRegression Normalized Data : \n')
print('RMSE: ', rmse(y_hat, y))
print('MAE: ', mae(y_hat, pd.Series(y)))
print("---------------------------")
